before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq odbc-postgresql unixodbc-dev git libjansson-dev libjansson4

language: c

compiler: gcc

addons:
  postgresql: "9.3"

env:
  global:
    - secure: TnTGMjGO4i2SgcDtqOKADL1/0iHI3SomEDqn2/9+5vepTmOxPTkEYSwgtcvw0HLBnB5rHFvpi5FcUZCXEbe9OuaR2re2nyQFOw5Cz03CB9L4iNwtlE1OUUhCPsKI7skrkhTjDxJ/eXdaKOY2ER6Wt55BzKaQysRSkf6ApJKbFjE=
    - PGVERSION="9.3"

before_script:
  - source $TRAVIS_BUILD_DIR/travis_linux_env.sh

script:
  - cd $IRODS_HOME
  - export CFLAGS=-fPIC ; make
  - cd $TRAVIS_BUILD_DIR

after_script:
#  - sudo -E -u postgres $TRAVIS_BUILD_DIR/setup_pgusers.sh
#  - sudo -E -u postgres $TRAVIS_BUILD_DIR/irodscontrol psetup
  - git clone https://github.com/wtsi-npg/baton.git baton && cd baton
  - ../build_baton_release.sh
#  - $TRAVIS_BUILD_DIR/smoke_test.sh

after_failure:
  - cat $IRODS_HOME/server/log/rodsLog.*

# after_success: cd $TRAVIS_BUILD_DIR ; tar -c -f irods.tar.gz -z --exclude='*.o' --exclude='*.c' iRODS/

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file: irods.tar.gz
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_BRANCH = travis-build"
    branch: travis-build

branches:
  only:
  - travis-build

notifications:
    email: false
